# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0269435b88cf581f931b5cfb641da28c3fa4f91120ae940b5a5b3746563ba2dfa251df3bb727f553e24d14ae6f4386fa25486c4161bfaece5543d65fff7e70b6

test:
  secret_key_base: a954ffc5a0e475c66d77fffa0a56b19a5d1c29acfb6df1f41722560e35e52bd6dc9bbb67a2cabf6aa3beefd84cd1cb05eafc5f2dee2c681e970a1ad20a203a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
